language: node_js
node_js:
- '10'
cache:
  directories:
  - "$HOME/.npm"
  - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_ec767382cef6_key -iv $encrypted_ec767382cef6_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- nvm install 'lts/*'
- npm i -g npm

install:
- npm install --no-audit --no-progress --quiet
- cp URL.js.develop src/constants/URLs.js
- npm run pack

after_success:
- shopt -s extglob
- mkdir build
- mv dist/* build
- tar -czf package.tgz build
- scp -o stricthostkeychecking=no -p $PORT -i ./deploy_key package.tgz $USER@$HOST:$DEPLOY_PATH/
- ssh -o stricthostkeychecking=no -p $PORT  -i ./deploy_key $USER@HOST $DEPLOY_PATH/deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
