sudo: required
language: node_js
node_js:
  - "10"

cache:
  directories:   
    - $HOME/.npm
    - node_modules

addons:
  chrome: stable
  apt:
    packages:
        - sshpass        
        
before_install:
  - nvm install 'lts/*'
  - npm i -g npm
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  
install:
  - npm install --no-audit --no-progress --quiet
  - cp URL.js.develop src/constants/URLs.js
  - npm run pack
  
after_success: 
  - shopt -s extglob
  - mkdir build
  - mv dist/* build
  - tar -czf package.tgz build
  - sshpass -p $DEPLOY_PASSWORD scp -o stricthostkeychecking=no -P $DEPLOY_PORT package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -p $DEPLOY_PASSWORD ssh -o stricthostkeychecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always  
